[project]
name = "pvninja"
version = "0.1.0"
description = "Full automation on top of SolarAssistant's MQTT, for Growatt TL-X/XH, TL3-XH"
authors = [
    {name = "Jimmi Bram"}
]
license = {text = "Apache 2.0"}
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "paho-mqtt (>=2.1.0,<3.0.0)",
    "flask (>=3.1.0,<4.0.0)",
    "flask-socketio (>=5.5.1,<6.0.0)",
    "nordpool (>=0.4.5,<0.5.0); python_version >= '3.13' and python_version < '4.0'"
]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
